# Generated by Django 6.0.2 on 2026-09-20 13:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=360)),
                ('year', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
                ('movie_image', models.ImageField(blank=True, null=True, upload_to='movie_pictures/')),
                ('director', models.TextField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
